using System;
using System.Collections.Generic;

#nullable disable

namespace SIP_NightAudit_Service.Service.HimsModels
{
    public partial class Msheet
    {
        public double? Id { get; set; }
        public double? ServerId { get; set; }
        public string ReferralNo { get; set; }
        public string UpdateStatus { get; set; }
        public string IdInscompany { get; set; }
        public string SyncBatchNo { get; set; }
        public string SyncBatchNoUpdate { get; set; }
        public string SyncBatchDelete { get; set; }
        public double? SyncInsert { get; set; }
        public string SyncUpdate { get; set; }
        public string SyncDelete { get; set; }
        public string PriceCurrency { get; set; }
        public string CurrencyRateDate { get; set; }
        public string CurrencyUsdRate { get; set; }
        public string CurrencyOriginalRate { get; set; }
        public string ClaimsDetailsId { get; set; }
        public string InvoiceNo { get; set; }
        public string ClaimTypeRe { get; set; }
        public string DiscPercent { get; set; }
        public string DiscAmount { get; set; }
        public string CoPaymentPercent { get; set; }
        public string CoPaymentAmount { get; set; }
        public string NatureofvisitLimit { get; set; }
        public string TypeofvisitLimit { get; set; }
        public string Visittype { get; set; }
        public string ServiceSpeciality { get; set; }
        public string IsDisputed { get; set; }
        public string DisputedDate { get; set; }
        public string UpdateDeleteStatus { get; set; }
        public string Company { get; set; }
        public string AuditUpdate { get; set; }
        public double? ProviderDataId { get; set; }
        public string InsCompany { get; set; }
        public string ProviderId { get; set; }
        public string MemberNo { get; set; }
        public string ProviderName { get; set; }
        public string ProviderIdMaster { get; set; }
        public string EmployerId { get; set; }
        public string EmployerCode { get; set; }
        public string UserId { get; set; }
        public string ProcessClaimNo { get; set; }
        public string ProviderRefNo { get; set; }
        public string AttendingOfficer { get; set; }
        public string Diagnosis { get; set; }
        public string DiagnosisCode { get; set; }
        public string IcdCode { get; set; }
        public string EyeOptical { get; set; }
        public string Toothnos { get; set; }
        public string TypeOfVisit { get; set; }
        public string NatureOfVisit { get; set; }
        public DateTime? DateOfConsultation { get; set; }
        public string DateOfActualConsultation { get; set; }
        public string DateOfAdmission { get; set; }
        public string DateOfDischarge { get; set; }
        public string ProviderItemId { get; set; }
        public string InsItemCode { get; set; }
        public string AuthorizationRequired { get; set; }
        public string AuthorizationCode { get; set; }
        public string Item { get; set; }
        public string ItemService { get; set; }
        public string ItemServiceType { get; set; }
        public string ItemClass { get; set; }
        public double? ItemDaysDiff { get; set; }
        public double? Qty { get; set; }
        public double? UnitPrice { get; set; }
        public double? TotalPrice { get; set; }
        public string QtyAwarded { get; set; }
        public string UnitPriceAwarded { get; set; }
        public string QtyFinance { get; set; }
        public string UnitPriceFinance { get; set; }
        public DateTime? DateAdded { get; set; }
        public DateTime? DateAddedShort { get; set; }
        public double? Dose { get; set; }
        public string DosageForm { get; set; }
        public string Frequency { get; set; }
        public double? NoOfDays { get; set; }
        public string Status { get; set; }
        public double? Awarded { get; set; }
        public string Comment { get; set; }
        public string CurrentLocation { get; set; }
        public string ActionStatus { get; set; }
        public string Supplied { get; set; }
        public string ValidationKey { get; set; }
        public string ValidationPin { get; set; }
        public string ServerPushStatus { get; set; }
        public DateTime? PushTime { get; set; }
        public string SubmittedStatus { get; set; }
        public DateTime? SubmitTime { get; set; }
        public string RxMemberId { get; set; }
        public string SmsSent { get; set; }
        public string PaymentStatus { get; set; }
        public string ApprovedQueryStatus { get; set; }
        public string QueryStatus { get; set; }
        public string ServerTimeUpdate { get; set; }
        public string DelStatus { get; set; }
        public string ProviderIdDataFor { get; set; }
        public string ProviderIdDataForText { get; set; }
        public string DecisionStatus { get; set; }
        public string DecisionReason { get; set; }
        public string DecisionReasonOther { get; set; }
        public string AuditStatus { get; set; }
        public string RxItemName { get; set; }
        public string RxBrandName { get; set; }
        public string RxCartegory { get; set; }
        public string RxPrescriptionName { get; set; }
        public string FinanceAuditStatus { get; set; }
        public string AuditTime { get; set; }
        public string AuditUserId { get; set; }
        public string AuditedBy { get; set; }
        public string PaymentType { get; set; }
        public string PregnancyStatus { get; set; }
        public string PregnancyWeeks { get; set; }
        public string PregnancyExpectedDelivery { get; set; }
        public string FinanceDecisionStatus { get; set; }
        public string FinanceDecisionReason { get; set; }
        public string FinanceDecisionReasonOther { get; set; }
        public string FinancialStatus { get; set; }
        public string ProviderNameDataFor { get; set; }
        public string ReferToAuditor { get; set; }
        public string ClaimType { get; set; }
        public string TopupAmt { get; set; }
        public string ApproveBalance { get; set; }
        public string BatchNo { get; set; }
        public string FinanceAuditTime { get; set; }
        public string FinanceAuditUserId { get; set; }
        public string FinanceAuditedBy { get; set; }
        public double? SyncInsertCounts { get; set; }
        public double? SyncUpdateCounts { get; set; }
        public string BookingNo { get; set; }
    }
}
